### ISSUE TITLE
Can you please add instructions how to use it?

### ISSUE THREAD

**Issue by munashige** [tfcollins/sphinx_pdf_theme#1]
Cannot find a way to get it work at all :)
And there is little to no info on how to work with simplepdf themes

**Comment by tfcollins** [comment]
Sorry this is a personal project. You'll need to use at your own risk. I would look at the upstream project https://github.com/useblocks/sphinx-simplepdf 
The only help I can offer is that it needs to be placed in the themes folder of the sphinx-simplepdf project and you need to tell the config its name (subfolder)

**Comment by munashige** [comment]
@tfcollins Thanks, I did figure it out :)
